### PR TITLE
Cleanup and generalization

### PR DESCRIPTION
**Pull request by jougs**
This cleans up and rewrites most of the stiffness tester by simplifying code and using an object oriented approach.

### CODE REVIEW

**Comment by jougs** [comment]
Apparently, `pip install pygsl` with the [error described here](https://stackoverflow.com/questions/46990136). I have no clue what this is about. Probably solving this requires spinning up an interactive debug build. I'm trying to look into this asap.

**Comment by clinssen** [comment]
I did a clean install on a Debian VM and things worked out of the box.

	sudo apt update
	sudo apt install libgsl0-dev gcc python3 python3-pip python3-dev python3-setuptools
	pip3 install wheel --user
	pip3 install numpy sympy --user
	pip3 install pygsl --user

libgsl-dev is version 2.3+dfsg-1 (amd64) and pygsl is version 2.3.0.1.

**Comment by clinssen** [comment]
Hi @jougs, I just noticed that this PR does not cover any files in the `tests` directory. This has one of the scripts complaining about not being able to import check_ode_system_for_stiffness(), which is probably right as it is now called StiffnessTester.check_stiffness(). Perhaps the files in `tests` were not git add-ed for this PR?

**Comment by clinssen** [comment]
@jougs: could you comment on why the factor 6 was changed to a 2 when comparing the implicit vs. explicit resolution? Compare:

https://github.com/nest/ode-toolbox/pull/12/files#diff-74891dc048b0d32d5d5c33deaafdb89bL485

https://github.com/nest/ode-toolbox/pull/12/files#diff-74891dc048b0d32d5d5c33deaafdb89bR361

**Comment by clinssen** [comment]
Currently, there are two failing stiffness tests: the one for the FitzHugh-Nagumo model, and the one for the Morris-Lecar.

For the first, the obtained step size values are near the original implicit/explicit decision threshold (avg_IMP: 0.1983999999999996 avg_EXP: 0.08188895735081046). Results might fluctuate slightly based on a multitude of factors, causing a change between an "implicit" and "explicit" verdict. With the new threshold (see my previous comment) this should no longer be a problem and I recommend changing the assertion in the test accordingly.

For the Morris-Lecar, I believe that the results are actually in accordance with the paper (and the original threshold). A stiffness test is performed with a temporal resolution of 0.2 ms and an accuracy of 1E-5. This corresponds to the top (blue) line in Figure 6 of Blundell et al. 2018, which indeed recommends the use of an explicit solver in this case. The test assertion should therefore be changed from "implicit" to "explicit".

**Comment by jougs** [comment]
@clinssen: The motivation for the change from factor 2 to 6 is explained in the [paper](https://www.frontiersin.org/articles/10.3389/fninf.2018.00050), last paragraph of sec. 3.3.1.

**Pull request merged**
