### PR TITLE
Use dictionaries rather than lists for initial values

### LINKED ISSUE #7: Fix order of `shape_state_variables` and `shape_state_updates` in the json
Why `shape_state_variables` and `shape_state_updates` are stored in the reversed order wrt their derivation order in the json output. But `shape_initial_values` are sorted by the derivation order? That should be fixed.

### PR DESCRIPTION
**Pull request by clinssen**
This fixes #7 by adding an integration test, which runs a simple alpha synapse/IAF neuron simulation on the basis of the returned analysis from ode-toolbox, and compares it to manually computed reference propagators and a numerical (RK45) simulation. Note that optimising the propagator matrix into a lower-triangular form (eq. 14 in Blundell et al. Front Neuroinform 2018) changes the semantics of the variables such that a direct comparison is no longer possible (unless the same rewrite is done in Python). We suggest adding a user configurable flag to optionally disable (or enable) this optimisation.

This PR fixes the root issue by insisting that initial values are specified as dictionaries, rather than lists. It is surprisingly easy to make mistakes when using the simple rule that "derivation order (d/dt)^i goes at index i in the list"; this PR forces the pertinent variable and derivative order to always be explicitly specified. For example, where before the initial values for an alpha-shaped postsynaptic kernel were specified as `["e/tau_syn_ex", "0"]`, they would now read `{"g_ex" : "0", "g_ex'" : "e/tau_syn_ex"}`.

### CODE REVIEW

**Comment by clinssen** [comment]
Note that the underflow issues were being caused by the following code:

https://github.com/nest/ode-toolbox/blob/509a1e8b17c0f36d7eb749812a6882ca7f1142b1/odetoolbox/stiffness.py#L33

The default setting for numpy/scipy underflow exception handling is "ignore". I currently left it at "warn" but I believe it can safely be set to ignore.

**Comment by jougs** [comment]
I changed the setting from `ignore` to `raise` in order to detect possible errors in the use of NumPy during my refactoring in #12. If it can safely be set back to `ignore`, I am happy with that, but would request the addition of a comment explaining the whereabouts of this.

**Comment by jougs** [comment]
@clinssen: Should I review and merge offline or should we go through this together in a VC/F2F meeting? Both ways would work for me.

**Comment by clinssen** [comment]
Closing because superseded by #19.

**Pull request closed without merging**
